### ISSUE TITLE
day08a - index shift

### ISSUE THREAD

**Issue by ivyONS** [timvisee/advent-of-code-2022#1]
Your code misses one tree from the example input (2nd digit on 3rd row) due to  missing '-1' in indexing

to fix, replace line 22-25 with:
```
                .scan(g[s - 1][i], |max, y| match (*max, g[s - y - 1][i]) {
                    (m, n) if n > m => {
                        *max = n;
                        Some(Some(i + (s - y - 1) * s))
```
similarly for columns.

Thank you for sharing your code - i just started learning rust and your code is very impressive - I've already learned some tricks from it :)

**Comment by timvisee** [comment]
Good catch. Thanks! I've just patched this.

Happy to see you found the solutions useful.
